"""report.py — EXPERIMENTS.md regeneration + paired-report builder.

Moved from multi_review.py legacy functions _format_fallback_label and
render_experiments_markdown, then extended with build_paired_report and
paired_report_filename per spec §10.1 / Task 14.
"""

from __future__ import annotations

import json
from pathlib import Path


REPORT_FORMAT_VERSION = 1


def _row_sort_key(r: dict) -> str:
    """Sort key: prefer started_at, fall back to timestamp."""
    return r.get("started_at", "") or r.get("timestamp", "") or ""


def _is_pair_eligible(row: dict) -> bool:
    """Return True if every reviewer in usage_by_reviewer has comparison_eligible: True.

    schema_version==1 rows pre-date per-reviewer telemetry and are grandfathered
    eligible. v2+ rows missing usage_by_reviewer are treated as ineligible —
    a missing field on a current-schema row signals a degraded harvest or a
    migrator that silently no-op'd, and counting those biases the
    next_recommended_order recommendation.
    """
    ubr = row.get("usage_by_reviewer")
    if not ubr:
        return row.get("schema_version") == 1
    return all(v.get("comparison_eligible", True) for v in ubr.values())


def render_experiments_markdown(*, log_path: Path, reports_dir: Path) -> str:
    """Read log_path JSONL and render the full EXPERIMENTS.md content.

    Owns JSONL reading, sorting, project grouping, and counter computation.
    reports_dir is used to surface paired-report file links.
    """
    # ---- Load rows ----
    rows: list[dict] = []
    if log_path.exists():
        for line in log_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError:
                pass  # skip malformed rows silently here; cmd_report warns

    rows.sort(key=_row_sort_key)

    # ---- Group by project and assign _order_in_project ----
    by_project: dict[str, list[dict]] = {}
    for r in rows:
        by_project.setdefault(r.get("project", "?"), []).append(r)
    for project_rows in by_project.values():
        project_rows.sort(key=_row_sort_key)
        for idx, r in enumerate(project_rows):
            r["_order_in_project"] = (
                "first" if idx == 0 else "second" if idx == 1 else f"#{idx + 1}"
            )

    # ---- Counters: only eligible pairs ----
    # "sessions_reference_first": projects where the FIRST eligible row is mode=reference
    # "sessions_inline_first": same for inline
    # We use eligible_first_mode per project: first row in the project where
    # _is_pair_eligible is True.
    sessions_reference_first = 0
    sessions_inline_first = 0
    for project_rows in by_project.values():
        eligible_rows = [r for r in project_rows if _is_pair_eligible(r)]
        if not eligible_rows:
            continue
        first_mode = eligible_rows[0].get("mode")
        if first_mode == "reference":
            sessions_reference_first += 1
        elif first_mode == "inline":
            sessions_inline_first += 1

    if sessions_reference_first <= sessions_inline_first:
        next_order = "reference-first"
    else:
        next_order = "inline-first"

    # ---- Notes / sidecars dirs ----
    notes_dir = log_path.parent / "notes"
    legacy_notes_dir = notes_dir / "legacy"

    parts: list[str] = []
    parts.append("# Inline-vs-reference comparison log\n")
    parts.append(
        "_Generated by `multi_review.py --report`. Do not edit by hand — "
        "your changes will be overwritten on the next regeneration. "
        "Source data: `runs/runs.jsonl`. Per-project narrative depth lives "
        "in `runs/notes/<project>-<YYYY-MM-DD>.md` sidecars._\n"
    )

    parts.append("## Status\n")
    parts.append(f"- sessions_reference_first: {sessions_reference_first}")
    parts.append(f"- sessions_inline_first: {sessions_inline_first}")
    parts.append(f"- **next_recommended_order: {next_order}**\n")
    parts.append(
        "Rule: `next_recommended_order` = mode whose count is lower; "
        "tie → alternate from the last-used order.\n"
    )

    parts.append("## Methodology\n")
    parts.append(
        "For a clean comparison run:\n"
        "- Run BOTH modes against identical inputs in the recommended order.\n"
        "- Run from separate sessions when possible so cache state doesn't "
        "bias claude's tool-call behaviour.\n"
        "- The harness writes one row to `runs/runs.jsonl` per run "
        "automatically. Pass `--no-harvest` to opt out for a given run.\n"
    )

    parts.append("## Run log\n")
    parts.append(
        "| Date | Project | Mode | Pair ID | Order | Prompt bytes | Wall | "
        "Output bytes | OK / Total | Notes |\n"
        "|------|---------|------|---------|-------|--------------|------|"
        "--------------|------------|-------|"
    )
    for r in rows:
        date = _row_sort_key(r)[:10] or "n/a"
        project = r.get("project", "?")
        mode = r.get("mode", "?")
        pair_id = r.get("pair_id") or ""
        order = r.get("_order_in_project", "?")
        pb = r.get("prompt_bytes")
        prompt_bytes = f"{pb:,}" if isinstance(pb, int) and pb > 0 else "n/a"
        wall_s = r.get("wall_seconds")
        wall = f"{wall_s:.1f}s" if isinstance(wall_s, (int, float)) else "n/a"
        ob = r.get("output_bytes")
        output_bytes = f"{ob:,}" if isinstance(ob, int) and ob > 0 else "n/a"
        # reviewers_succeeded can be int (v2) or list (v1)
        rs = r.get("reviewers_succeeded") or []
        ok = rs if isinstance(rs, int) else len(rs)
        rf = r.get("reviewers_failed") or []
        total_failed = rf if isinstance(rf, int) else len(rf)
        total = ok + total_failed
        notes = (r.get("notes") or "").replace("|", "\\|").replace("\n", " ")
        # Escape pair_id for table
        pair_display = (pair_id or "").replace("|", "\\|")
        parts.append(
            f"| {date} | {project} | {mode} | {pair_display} | {order} | {prompt_bytes} | "
            f"{wall} | {output_bytes} | {ok}/{total} | {notes} |"
        )
    parts.append("")

    parts.append("## Per-project narrative\n")
    by_project_dates: dict[str, set[str]] = {}
    for r in rows:
        by_project_dates.setdefault(r.get("project", "?"), set()).add(
            _row_sort_key(r)[:10]
        )
    found_any = False
    for project in sorted(by_project_dates):
        for date in sorted(by_project_dates[project]):
            if not date:
                continue
            sidecar = notes_dir / f"{project}-{date}.md"
            if sidecar.exists():
                found_any = True
                parts.append(f"### {project} ({date})\n")
                parts.append(sidecar.read_text(encoding="utf-8").strip())
                parts.append("")
    if not found_any:
        parts.append(
            "_No sidecar narrative files found in `runs/notes/`. "
            "Drop `runs/notes/<project>-<YYYY-MM-DD>.md` files to add per-run "
            "context — they're stitched in here at report time._\n"
        )

    if reports_dir.exists():
        report_files = sorted(p for p in reports_dir.glob("*.md") if p.is_file())
        if report_files:
            parts.append("## Paired reports\n")
            for f in report_files:
                rel = f"reports/{f.name}"
                parts.append(f"- [{f.stem}]({rel})")
            parts.append("")

    parts.append("## Open questions\n")
    parts.append(
        "- Is the gemini-quota-cascade real or perceived? Need a session "
        "where inline runs first against fresh quota.\n"
        "- Does the diversity-of-findings benefit hold for prompts under "
        "100KB? Both Guestflow data points are large reviews.\n"
        "- Should `--mode auto` exist (run both for prompts ≥ N bytes)? "
        "Backlog candidate.\n"
    )

    # ---- Pre-schema-stabilisation narrative ----
    if legacy_notes_dir.exists():
        legacy_files = sorted(legacy_notes_dir.iterdir())
        if legacy_files:
            parts.append("## Pre-schema-stabilisation narrative\n")
            for f in legacy_files:
                if f.is_file():
                    parts.append(f"- legacy/{f.name}")
            parts.append("")

    return "\n".join(parts).rstrip() + "\n"


def build_paired_report(
    *,
    log_path: Path,
    pair_id: "str | None",
    out_path: Path,
    headline: "str | None",
    mode_divergence: "str | None",
    per_reviewer_notes: "str | dict | None",
    # Legacy-mode kwargs (used when pair_id is None — migrator path)
    legacy_run_ids: "list[str] | None" = None,
    project: "str | None" = None,
    date: "str | None" = None,
    synth_pair_id: "str | None" = None,
) -> None:
    """Write a format-C paired-report file to out_path.

    Normal mode (pair_id is not None):
      Reads both pass rows for pair_id from log_path, computes pair-level
      comparison_eligible flag, then writes YAML frontmatter + body sections.

    Legacy mode (pair_id is None):
      Uses synth_pair_id for the frontmatter pair_id field.
      Derives rows from legacy_run_ids matched against the log by synthetic
      run-ID (CandidatePair.synth_run_id).

    out_path's parent directory must already exist.
    """
    if pair_id is None:
        # Legacy / migration path
        from multi_review.core.sidecar import CandidatePair  # local import avoids circular

        all_rows: list[dict] = []
        if log_path.exists():
            for line in log_path.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if not line:
                    continue
                try:
                    all_rows.append(json.loads(line))
                except json.JSONDecodeError:
                    continue

        pair_rows: list[dict] = []
        if legacy_run_ids:
            for row in all_rows:
                if CandidatePair.synth_run_id(row) in legacy_run_ids:
                    pair_rows.append(row)

        pair_eligible = _compute_pair_eligible(pair_rows)
        eligible_str = "true" if pair_eligible else "false"
        effective_pair_id = synth_pair_id or "legacy-unknown"

        frontmatter = (
            "---\n"
            f"report_format_version: {REPORT_FORMAT_VERSION}\n"
            f"pair_id: {effective_pair_id}\n"
            f"pair_type: paired\n"
            f"comparison_eligible: {eligible_str}\n"
            "---\n"
        )
    else:
        # Normal path
        # Load rows for this pair
        pair_rows = []
        if log_path.exists():
            for line in log_path.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if not line:
                    continue
                try:
                    r = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if r.get("pair_id") == pair_id:
                    pair_rows.append(r)

        # Compute pair-level comparison_eligible:
        # all reviewers in ALL pass rows must have comparison_eligible: True
        pair_eligible = _compute_pair_eligible(pair_rows)

        eligible_str = "true" if pair_eligible else "false"

        frontmatter = (
            "---\n"
            f"report_format_version: {REPORT_FORMAT_VERSION}\n"
            f"pair_id: {pair_id}\n"
            f"pair_type: paired\n"
            f"comparison_eligible: {eligible_str}\n"
            "---\n"
        )

    headline_text = headline or "_TBD — synthesizer will fill_"
    mode_div_text = mode_divergence or "_TBD — synthesizer will fill_"

    body_parts = [frontmatter, ""]
    body_parts.append(f"## Headline\n\n{headline_text}\n")
    body_parts.append(f"## Mode-divergence observations\n\n{mode_div_text}\n")

    if per_reviewer_notes:
        body_parts.append("## Per-reviewer notes\n")
        if isinstance(per_reviewer_notes, str):
            body_parts.append(per_reviewer_notes)
        else:
            for cli, text in per_reviewer_notes.items():
                body_parts.append(f"### {cli}\n\n{text}\n")
    else:
        body_parts.append(
            "## Per-reviewer notes\n\n_TBD — synthesizer will fill_\n"
        )

    out_path.write_text("\n".join(body_parts), encoding="utf-8")


def _compute_pair_eligible(pair_rows: list[dict]) -> bool:
    """Pair-level eligibility: all reviewers in all rows must be comparable.

    Per spec §7.1: a reviewer is comparable iff BOTH passes have
    comparison_eligible: True for that reviewer.
    """
    if not pair_rows:
        return False
    for row in pair_rows:
        ubr = row.get("usage_by_reviewer")
        if not ubr:
            if row.get("schema_version") == 1:
                continue
            return False
        for rv in ubr.values():
            if not rv.get("comparison_eligible", True):
                return False
    return True


def paired_report_filename(project: str, date: str, pair_id: str) -> str:
    """Return the canonical filename for a paired report.

    Format: <project>-<date>-<pair-id>.md  (spec §4.2 / §10.1)
    Collision handling (auto-suffix) is the caller's responsibility.
    """
    return f"{project}-{date}-{pair_id}.md"
